### ISSUE TITLE
Unable to build from source on macOS

### ISSUE THREAD

**Issue by machawk1** [DocNow/hydrator#9]
`npm run dev` works well for testing the hot-swappable version but when I try to package the app using `npm run package-all` I receive the following error on macOS 10.12.2, node v7.2.1 and the packaging process fails to build the binary.

```sh
Error: Cannot check wine version: Error: Exit code: ENOENT. spawn wine ENOENT
    at /Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/packager.ts:314:13
    at Generator.throw (<anonymous>)
From previous event:
    at checkWineVersion (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/out/packager.js:57:22)
    at /Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/packager.ts:143:17
From previous event:
    at Packager.doBuild (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/out/packager.js:275:11)
    at /Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/packager.ts:114:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/out/packager.js:227:11)
    at /Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/builder.ts:249:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/out/builder.js:90:21)
    at Object.<anonymous> (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "package-all"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.10.0 package-all: `npm run build && build -mwl`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.10.0 package-all script 'npm run build && build -mwl'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && build -mwl
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/machawk1/Downloads/hydrator/npm-debug.log
```

**Comment by edsu** [comment]
Does it help if you:

     brew install wine

🍷

**Comment by machawk1** [comment]
@edsu, that seems like a big hammer but is also recommended along w/ `brew install mono` on macOS per https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#os-x . Do you anticipate any issues in having `"package-mac": "npm run build && build --mac"` in the `package.json` file to allow for single-platform building? I tried running `npm run build && build --mac` but bash/OSX complains about not being able to find `build` nor does `sh build ...` or `./build ...` work either.

I'll report back once `brew install wine` is complete. 🍺

**Comment by edsu** [comment]
Just run "npm run package" if all you want is your native package built.

**Comment by edsu** [comment]
Oops I didn't mean to close just yet. It sounds like the readme should be improved to avoid people running into this?

**Comment by machawk1** [comment]
@edsu That worked and was much simpler. I added https://github.com/DocNow/hydrator/pull/10 to provide this info in the README.

**Comment by edsu** [comment]
Thanks! :cake:

**Comment by machawk1** [comment]
For the sake of completeness, `npm run package-all` still fails even after installing wine using homebrew per above.

```sh
$ npm run package-all

> electron-react-boilerplate@0.10.0 package-all /Users/machawk1/Downloads/hydrator
> npm run build && build -mwl


> electron-react-boilerplate@0.10.0 build /Users/machawk1/Downloads/hydrator
> npm run build-main && npm run build-renderer


> electron-react-boilerplate@0.10.0 build-main /Users/machawk1/Downloads/hydrator
> cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.electron.js --progress --profile --colors

1738ms build modules      
14ms seal
11ms optimize
15ms hashing
31ms create chunk assets
13344ms additional chunk assets
428ms optimize chunk assets
2ms optimize assets 
40ms emit
Hash: c08529c464a0e7895c99
Version: webpack 1.14.0
Time: 15633ms
            Asset     Size  Chunks             Chunk Names
    ./app/main.js   267 kB       0  [emitted]  main
./app/main.js.map  1.37 MB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built]
       factory:1ms building:1ms = 2ms
    + 337 hidden modules

> electron-react-boilerplate@0.10.0 build-renderer /Users/machawk1/Downloads/hydrator
> cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.production.js --progress --profile --colors

7050ms build modules      
29ms seal
40ms optimize
18ms hashing
49ms create chunk assets
11185ms additional chunk assets
31ms optimize chunk assets
118ms optimize assets
12ms emit
Hash: 43739f29f1b7abbbf84a
Version: webpack 1.14.0
Time: 18555ms
        Asset       Size  Chunks             Chunk Names
    bundle.js     349 kB       0  [emitted]  main
    style.css     3.4 kB       0  [emitted]  main
bundle.js.map    3.46 kB       0  [emitted]  main
style.css.map  268 bytes       0  [emitted]  main
  ../app.html  775 bytes          [emitted]  
   [0] multi main 40 bytes {0} [built]
       factory:0ms building:2ms = 2ms
    + 597 hidden modules
Child html-webpack-plugin for "../app.html":
        + 3 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
No native production dependencies
Packaging for darwin x64 using electron 1.4.13 to release/mac
⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
Building macOS zip
Building DMG
Skip app dependencies rebuild because platform is different
Packaging for linux x64 using electron 1.4.13 to release/linux-unpacked
Building AppImage for arch x64
Skip app dependencies rebuild because platform is different
Packaging for win32 x64 using electron 1.4.13 to release/win-unpacked
Packaging NSIS installer for arch x64
Building NSIS installer
Building deb
Error: Exit code: 1. Command failed: /Users/machawk1/Library/Caches/electron-builder/fpm/fpm-1.6.3-20150715-2.2.2/fpm -s dir -t deb --architecture amd64 --name Hydrator --force --after-install /var/folders/06/byy6nv8s7rx0szkj77mgpzth0000gn/T/electron-builder-K1qmXW/0-4-after-install --after-remove /var/folders/06/byy6nv8s7rx0szkj77mgpzth0000gn/T/electron-builder-K1qmXW/0-5-after-remove --description 
 A desktop utility to hydrate Twitter ID datasets. --maintainer Ed Summers <ehs@pobox.com> --vendor Ed Summers <ehs@pobox.com> --version 0.0.2 --package /Users/machawk1/Downloads/hydrator/release/Hydrator_0.0.2_amd64.deb --url https://github.com/chentsulin/electron-react-boilerplate --deb-compression xz --depends gconf2 --depends gconf-service --depends libnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --license MIT /Users/machawk1/Downloads/hydrator/release/linux-unpacked/=/opt/Hydrator /Users/machawk1/Downloads/hydrator/resources/icons/128x128.png=/usr/share/icons/hicolor/128x128/apps/hydrator.png /Users/machawk1/Downloads/hydrator/resources/icons/16x16.png=/usr/share/icons/hicolor/16x16/apps/hydrator.png /Users/machawk1/Downloads/hydrator/resources/icons/24x24.png=/usr/share/icons/hicolor/24x24/apps/hydrator.png /Users/machawk1/Downloads/hydrator/resources/icons/256x256.png=/usr/share/icons/hicolor/256x256/apps/hydrator.png /Users/machawk1/Downloads/hydrator/resources/icons/32x32.png=/usr/share/icons/hicolor/32x32/apps/hydrator.png /Users/machawk1/Downloads/hydrator/resources/icons/48x48.png=/usr/share/icons/hicolor/48x48/apps/hydrator.png /Users/machawk1/Downloads/hydrator/resources/icons/512x512.png=/usr/share/icons/hicolor/512x512/apps/hydrator.png /Users/machawk1/Downloads/hydrator/resources/icons/64x64.png=/usr/share/icons/hicolor/64x64/apps/hydrator.png /Users/machawk1/Downloads/hydrator/resources/icons/96x96.png=/usr/share/icons/hicolor/96x96/apps/hydrator.png /var/folders/06/byy6nv8s7rx0szkj77mgpzth0000gn/T/electron-builder-K1qmXW/0-1-Hydrator.desktop=/usr/share/applications/hydrator.desktop

{:timestamp=>"2017-01-04T18:41:51.577588-0500", :message=>"Debian tools (dpkg/apt) don't do well with packages that use capital letters in the name. In some cases it will automatically downcase them, in others it will not. It is confusing. Best to not use any capital letters at all. I have downcased the package name for you just to be safe.", :oldname=>"Hydrator", :fixedname=>"hydrator", :level=>:warn}
{:timestamp=>"2017-01-04T18:41:51.584532-0500", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2017-01-04T18:41:51.964668-0500", :message=>"Need executable '[\"gnutar\", \"gtar\"]' to convert dir to deb", :level=>:error}

    at /Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/util/util.ts:77:16
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
From previous event:
    at exec (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/util/util.ts:55:3)
    at /Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/targets/fpm.ts:166:11
    at Generator.next (<anonymous>)
From previous event:
    at FpmTarget.build (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/out/targets/fpm.js:228:11)
    at default.each.it (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/platformPackager.ts:173:87)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at postAsyncTasks.push.default.map.then (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/platformPackager.ts:173:35)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/platformPackager.ts:173:8)
    at /Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/platformPackager.ts:168:10
From previous event:
    at LinuxPackager.pack (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/out/platformPackager.js:219:11)
    at /Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/packager.ts:146:22
From previous event:
    at Packager.doBuild (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/out/packager.js:275:11)
    at /Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/packager.ts:114:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/out/packager.js:227:11)
    at /Users/machawk1/Downloads/hydrator/node_modules/electron-builder/src/builder.ts:249:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/out/builder.js:90:21)
    at Object.<anonymous> (/Users/machawk1/Downloads/hydrator/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "package-all"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.10.0 package-all: `npm run build && build -mwl`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.10.0 package-all script 'npm run build && build -mwl'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && build -mwl
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/machawk1/Downloads/hydrator/npm-debug.log
$ 
```

**Comment by edsu** [comment]
From the (voluminous) error message It looks like you need gnutar:

    brew install gnu-tar
